from argparse import ArgumentParser
from xai_components.base import SubGraphExecutor
from xai_components.xai_plotting.probabilistic_plot import PlotNormalLikelihoodJoy, PlotNormalLikelihood, PlotMarginals, ArvizObject, PlotPrior
from xai_components.xai_probabilistic_models.probabilistic_models_I import PyroModel
from xai_components.xai_probability_distributions.probabilistic_distributions import Normal, Gamma
from xai_components.xai_pyro.probabilistic_node import Sample, PriorPredictive, PosteriorPredictive, MCMC, NUTS, RunMCMC

def main(args):
    ctx = {}
    ctx['args'] = args
    c_0 = NUTS()
    c_1 = Sample()
    c_2 = Gamma()
    c_3 = Normal()
    c_4 = PyroModel()
    c_5 = PriorPredictive()
    c_6 = ArvizObject()
    c_7 = PlotPrior()
    c_8 = PlotNormalLikelihood()
    c_9 = PlotNormalLikelihoodJoy()
    c_10 = PlotMarginals()
    c_11 = RunMCMC()
    c_12 = PosteriorPredictive()
    c_13 = MCMC()
    c_14 = Sample()
    c_15 = Sample()
    c_16 = Normal()
    c_0.model = c_4.model
    c_1.name.value = '$\\sigma$'
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_1.fn = c_2.fn
    c_2.concentration.value = 0.3
    c_2.rate.value = 3.01
    c_3.mean.value = 2.07
    c_3.std.value = 0.07
    c_4.arg1 = c_15.sample
    c_5.model = c_4.model
    c_5.model = c_4.model
    c_5.model = c_4.model
    c_5.model = c_4.model
    c_5.model = c_4.model
    c_5.num_samples.value = 20
    c_6.mcmc = c_13.mcmc
    c_6.prior_predictive_values = c_5.prior
    c_6.posterior_predictive_values = c_12.posterior_predictive
    c_7.az_data = c_6.az_data
    c_7.az_data = c_6.az_data
    c_8.az_data = c_6.az_data
    c_8.mean_sample_name.value = '$\\mu$'
    c_8.std_sample_name.value = '$\\sigma$'
    c_8.y_sample_name.value = '$y$'
    c_9.az_data = c_6.az_data
    c_9.mean_sample_name.value = '$\\mu$'
    c_9.std_sample_name.value = '$\\sigma$'
    c_9.y_sample_name.value = '$y$'
    c_10.az_data = c_6.az_data
    c_10.sample_1_name.value = '$\\mu$'
    c_10.sample_2_name.value = '$\\sigma$'
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_11.mcmc = c_13.mcmc
    c_12.model = c_4.model
    c_12.MCMC = c_13.mcmc
    c_12.num_samples.value = 20
    c_13.NUTS = c_0.NUTS
    c_13.num_samples.value = 50
    c_13.num_chains.value = 1
    c_14.name.value = '$\\mu$'
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_14.fn = c_3.fn
    c_15.name.value = '$y$'
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.fn = c_16.fn
    c_15.obs.value = [2.12, 2.06, 2.08, 2.05, 2.08, 2.09, 2.19, 2.07, 2.16, 2.11, 2.13, 1.92]
    c_16.mean = c_14.sample
    c_16.std = c_1.sample
    c_0.next = c_13
    c_1.next = c_16
    c_2.next = c_1
    c_3.next = c_14
    c_4.next = c_5
    c_5.next = c_0
    c_6.next = c_7
    c_7.next = c_8
    c_8.next = c_9
    c_9.next = c_10
    c_10.next = None
    c_11.next = c_12
    c_12.next = c_6
    c_13.next = c_11
    c_14.next = c_2
    c_15.next = c_4
    c_16.next = c_15
    next_component = c_3
    while next_component:
        next_component = next_component.do(ctx)
if __name__ == '__main__':
    parser = ArgumentParser()
    main(parser.parse_args())
    print('\nFinished Executing')